// Mock data for GitHub Pages demo mode
// This provides realistic sample data so the app looks fully functional

const now = new Date();
const daysAgo = (n) => new Date(now.getTime() - n * 86400000).toISOString();

export const mockUser = {
  id: 1,
  username: "demo_user",
  email: "demo@espressotracker.app",
  role: "ADMIN",
};

export const mockBeans = [
  {
    id: 1,
    beanName: "Ethiopia Yirgacheffe",
    roasterName: "Counter Culture Coffee",
    roastLevel: "LIGHT",
    origin: "Yirgacheffe, Ethiopia",
    tastingNotes: "Blueberry, jasmine, silky body, bright acidity",
    createdAt: daysAgo(45),
  },
  {
    id: 2,
    beanName: "Colombia El Paraiso",
    roasterName: "Onyx Coffee Lab",
    roastLevel: "MEDIUM",
    origin: "Cauca, Colombia",
    tastingNotes: "Caramel, red apple, milk chocolate, clean finish",
    createdAt: daysAgo(30),
  },
  {
    id: 3,
    beanName: "Kenya Gachatha",
    roasterName: "Intelligentsia Coffee",
    roastLevel: "MEDIUM_LIGHT",
    origin: "Nyeri, Kenya",
    tastingNotes: "Blackcurrant, tomato, winey acidity, complex",
    createdAt: daysAgo(25),
  },
  {
    id: 4,
    beanName: "Guatemala Finca El Injerto",
    roasterName: "Stumptown Coffee",
    roastLevel: "MEDIUM_DARK",
    origin: "Huehuetenango, Guatemala",
    tastingNotes: "Dark chocolate, toffee, stone fruit, full body",
    createdAt: daysAgo(20),
  },
  {
    id: 5,
    beanName: "Brazil Fazenda Santa Ines",
    roasterName: "Blue Bottle Coffee",
    roastLevel: "DARK",
    origin: "Minas Gerais, Brazil",
    tastingNotes: "Peanut, cocoa, low acidity, creamy body",
    createdAt: daysAgo(15),
  },
  {
    id: 6,
    beanName: "Costa Rica Las Lajas",
    roasterName: "Verve Coffee Roasters",
    roastLevel: "LIGHT",
    origin: "Central Valley, Costa Rica",
    tastingNotes: "Honey, orange zest, floral, sparkling acidity",
    createdAt: daysAgo(10),
  },
  {
    id: 7,
    beanName: "Panama Geisha",
    roasterName: "Hacienda La Esmeralda",
    roastLevel: "LIGHT",
    origin: "Boquete, Panama",
    tastingNotes: "Jasmine, bergamot, tropical fruit, tea-like body",
    createdAt: daysAgo(7),
  },
  {
    id: 8,
    beanName: "Sumatra Mandheling",
    roasterName: "Heart Coffee Roasters",
    roastLevel: "DARK",
    origin: "Aceh, Sumatra",
    tastingNotes: "Herbal, cedar, dark chocolate, heavy body, low acid",
    createdAt: daysAgo(5),
  },
];

// Helper to get bean name from ID
const beanNameById = (id) =>
  mockBeans.find((b) => b.id === id)?.beanName || "Unknown Bean";

export const mockBrewLogs = [
  {
    id: 1,
    beanId: 1,
    beanName: beanNameById(1),
    doseGrams: 18,
    yieldGrams: 36,
    extractionTimeSeconds: 28,
    grindSetting: "2.2",
    rating: 4,
    notes: "Bright and fruity, excellent shot. Slight channeling at the end.",
    createdAt: daysAgo(40),
  },
  {
    id: 2,
    beanId: 1,
    beanName: beanNameById(1),
    doseGrams: 18,
    yieldGrams: 40,
    extractionTimeSeconds: 30,
    grindSetting: "2.3",
    rating: 5,
    notes: "Perfect extraction. Blueberry notes really popped. Best shot yet.",
    createdAt: daysAgo(38),
  },
  {
    id: 3,
    beanId: 2,
    beanName: beanNameById(2),
    doseGrams: 19,
    yieldGrams: 38,
    extractionTimeSeconds: 27,
    grindSetting: "2.0",
    rating: 3,
    notes: "Good but slightly under-extracted. Need finer grind.",
    createdAt: daysAgo(28),
  },
  {
    id: 4,
    beanId: 2,
    beanName: beanNameById(2),
    doseGrams: 19,
    yieldGrams: 42,
    extractionTimeSeconds: 32,
    grindSetting: "1.8",
    rating: 4,
    notes: "Much better. Caramel sweetness came through nicely.",
    createdAt: daysAgo(26),
  },
  {
    id: 5,
    beanId: 3,
    beanName: beanNameById(3),
    doseGrams: 18,
    yieldGrams: 36,
    extractionTimeSeconds: 29,
    grindSetting: "2.1",
    rating: 5,
    notes: "Incredible complexity. Blackcurrant and wine notes. A masterpiece.",
    createdAt: daysAgo(22),
  },
  {
    id: 6,
    beanId: 4,
    beanName: beanNameById(4),
    doseGrams: 20,
    yieldGrams: 40,
    extractionTimeSeconds: 26,
    grindSetting: "2.4",
    rating: 4,
    notes: "Rich and chocolatey. Great body. Would go well with milk.",
    createdAt: daysAgo(18),
  },
  {
    id: 7,
    beanId: 5,
    beanName: beanNameById(5),
    doseGrams: 20,
    yieldGrams: 35,
    extractionTimeSeconds: 25,
    grindSetting: "2.5",
    rating: 3,
    notes:
      "Classic dark roast profile. Peanut notes dominant. Good for daily driver.",
    createdAt: daysAgo(12),
  },
  {
    id: 8,
    beanId: 6,
    beanName: beanNameById(6),
    doseGrams: 18,
    yieldGrams: 37,
    extractionTimeSeconds: 30,
    grindSetting: "2.0",
    rating: 4,
    notes: "Honey sweetness was prominent. Orange acidity balanced well.",
    createdAt: daysAgo(8),
  },
  {
    id: 9,
    beanId: 7,
    beanName: beanNameById(7),
    doseGrams: 15,
    yieldGrams: 30,
    extractionTimeSeconds: 35,
    grindSetting: "1.5",
    rating: 5,
    notes: "Absolutely stunning. Floral and tea-like. Worth every penny.",
    createdAt: daysAgo(4),
  },
  {
    id: 10,
    beanId: 8,
    beanName: beanNameById(8),
    doseGrams: 19,
    yieldGrams: 34,
    extractionTimeSeconds: 24,
    grindSetting: "2.6",
    rating: 3,
    notes:
      "Earthy and bold. Low acidity as expected. Good for afternoon pick-me-up.",
    createdAt: daysAgo(2),
  },
];

export const mockAnalytics = {
  totalVisits: 117,
  visitsToday: 7,
  totalBeans: 8,
  totalBrewLogs: 10,
  averageRating: 4.0,
  visitTrend: [
    { date: "2026-07-12", count: 12 },
    { date: "2026-07-13", count: 8 },
    { date: "2026-07-14", count: 15 },
    { date: "2026-07-15", count: 10 },
    { date: "2026-07-16", count: 22 },
    { date: "2026-07-17", count: 18 },
    { date: "2026-07-18", count: 25 },
    { date: "2026-07-19", count: 7 },
  ],
  geoDistribution: [
    { country: "United States", count: 45 },
    { country: "Germany", count: 12 },
    { country: "United Kingdom", count: 10 },
    { country: "Canada", count: 8 },
    { country: "Brazil", count: 6 },
  ],
  topBeans: [
    {
      id: 7,
      beanName: "Panama Geisha",
      visitCount: 34,
      averageRating: 5.0,
      brewCount: 1,
    },
    {
      id: 3,
      beanName: "Kenya Gachatha",
      visitCount: 28,
      averageRating: 5.0,
      brewCount: 1,
    },
    {
      id: 1,
      beanName: "Ethiopia Yirgacheffe",
      visitCount: 22,
      averageRating: 4.5,
      brewCount: 2,
    },
    {
      id: 2,
      beanName: "Colombia El Paraiso",
      visitCount: 18,
      averageRating: 3.5,
      brewCount: 2,
    },
    {
      id: 4,
      beanName: "Guatemala Finca El Injerto",
      visitCount: 15,
      averageRating: 4.0,
      brewCount: 1,
    },
  ],
  topBrews: [
    {
      id: 5,
      beanName: "Kenya Gachatha",
      rating: 5,
      doseGrams: 18,
      yieldGrams: 36,
      extractionTimeSeconds: 29,
    },
    {
      id: 9,
      beanName: "Panama Geisha",
      rating: 5,
      doseGrams: 15,
      yieldGrams: 30,
      extractionTimeSeconds: 35,
    },
    {
      id: 2,
      beanName: "Ethiopia Yirgacheffe",
      rating: 5,
      doseGrams: 18,
      yieldGrams: 40,
      extractionTimeSeconds: 30,
    },
    {
      id: 1,
      beanName: "Ethiopia Yirgacheffe",
      rating: 4,
      doseGrams: 18,
      yieldGrams: 36,
      extractionTimeSeconds: 28,
    },
    {
      id: 4,
      beanName: "Colombia El Paraiso",
      rating: 4,
      doseGrams: 19,
      yieldGrams: 42,
      extractionTimeSeconds: 32,
    },
  ],
  beanPerformance: [
    { beanName: "Ethiopia Yirgacheffe", avgRating: 4.5, brewCount: 2 },
    { beanName: "Colombia El Paraiso", avgRating: 3.5, brewCount: 2 },
    { beanName: "Kenya Gachatha", avgRating: 5.0, brewCount: 1 },
    { beanName: "Guatemala Finca El Injerto", avgRating: 4.0, brewCount: 1 },
    { beanName: "Brazil Fazenda Santa Ines", avgRating: 3.0, brewCount: 1 },
    { beanName: "Costa Rica Las Lajas", avgRating: 4.0, brewCount: 1 },
    { beanName: "Panama Geisha", avgRating: 5.0, brewCount: 1 },
    { beanName: "Sumatra Mandheling", avgRating: 3.0, brewCount: 1 },
  ],
  extractionRatios: [
    { doseGrams: 18, yieldGrams: 36, rating: 4 },
    { doseGrams: 18, yieldGrams: 40, rating: 5 },
    { doseGrams: 19, yieldGrams: 38, rating: 3 },
    { doseGrams: 19, yieldGrams: 42, rating: 4 },
    { doseGrams: 18, yieldGrams: 36, rating: 5 },
    { doseGrams: 20, yieldGrams: 40, rating: 4 },
    { doseGrams: 20, yieldGrams: 35, rating: 3 },
    { doseGrams: 18, yieldGrams: 37, rating: 4 },
    { doseGrams: 15, yieldGrams: 30, rating: 5 },
    { doseGrams: 19, yieldGrams: 34, rating: 3 },
  ],
  ratingDistribution: [
    { rating: "1 Star", count: 0 },
    { rating: "2 Stars", count: 0 },
    { rating: "3 Stars", count: 3 },
    { rating: "4 Stars", count: 4 },
    { rating: "5 Stars", count: 3 },
  ],
};
